### ISSUE TITLE
Signing with Ed25519

### ISSUE THREAD

**Issue by noughtmare** [ZHaskell/z-botan#18]
I think there should be `Pure` and `Ed25519ph` constructors for the `EMSA` data type specifically for signing with `Ed25519`. See the implementation here: https://botan.randombit.net/doxygen/classBotan_1_1Ed25519__PrivateKey.html#a4cd89328de0b45a352f35e40a8fb5db2

> ```cpp
>    {
>    if(provider == "base" || provider.empty())
>       {
>       if(params == "" || params == "Identity" || params == "Pure")
>          return std::unique_ptr<PK_Ops::Signature>(new Ed25519_Pure_Sign_Operation(*this));
>       else if(params == "Ed25519ph")
>          return std::unique_ptr<PK_Ops::Signature>(new Ed25519_Hashed_Sign_Operation(*this, "SHA-512", true));
>       else
>          return std::unique_ptr<PK_Ops::Signature>(new Ed25519_Hashed_Sign_Operation(*this, params, false));
>       }
>    throw Provider_Not_Found(algo_name(), provider);
>    }
> ```

The `params` variable here is the `emsa` from the constructor of `PK_Signer`: https://botan.randombit.net/doxygen/classBotan_1_1PK__Signer.html#a1eab234db0d01f3d842758c7e07a5329

**Comment by alissa-tung** [comment]
See also `https://github.com/ZHaskell/botan/blob/release-haskell-Z/src/tests/data/pubkey/ed25519.vec`.

**Comment by winterland1989** [comment]
Done in [v0.3](https://hackage.haskell.org/package/Z-Botan-0.3.0.0), thanks!
